import type { Metadata } from "next";
import './styles/globals.scss'
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const rotisBold = localFont({
  src: "./fonts/ATRotisSemiSans.ttf",
  variable: "--font-rotis-bold",
});

const rotisSemi = localFont({
  src: "./fonts/ATRotisSemiSans.ttf",
  variable: "--font-rotis-semi",
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${rotisBold.variable} ${rotisSemi.variable}`}
        
      >
        {children}
      </body>
    </html>
  );
}
